AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scalable and Cost-Effective Cloud Infrastructure for Reporting Platform as a Capstone Project

Parameters:
  DBName:
    Type: String
    Default: reporting_platform_db
    Description: The database name for the RDS instance.
  DBUsername:
    Type: String
    Default: postgres
    Description: Master username for the RDS instance.
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for the RDS instance (secret).

Resources:
  ReportingPlatformBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-reports-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldReports"
            Status: "Enabled"
            ExpirationInDays: 30

  ReportingPlatformRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      StorageType: gp2
      AllocatedStorage: '20'
      MultiAZ: false
      PubliclyAccessible: true
      Engine: postgres
      EngineVersion: '16.1'
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      BackupRetentionPeriod: 0

  ReportingPlatformAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"

  ReportingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handler
      Runtime: nodejs24.x
      Policies:
        - SSMParameterReadPolicy:
          ParameterName: /gabaynet/reporting-platform/*
        - S3CrudPolicy:
          BucketName: !Ref ReportingPlatformBucket
        - Statement:
          - Effect: Allow
            Action:
            - "rds-db:connect"
            - "rds:DescribeDBInstances"
            Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ReportingPlatformAPI
      Environment:
        Variables: 
          DB_USER: !Ref DBUsername
          DB_HOST: !GetAtt ReportingPlatformRDS.Endpoint.Address
          DB_NAME: !Ref DBName
          DB_PASS_PARAM: /gabaynet/reporting-platform/db-password
          DB_PORT: '5432'
          JWT_SECRET_PARAM: /gabaynet/reporting-platform/jwt-secret
          JWT_EXPIRES_IN: 2h
          AWS_REGION: ap-southeast-1
          AWS_BUCKET_NAME: !Ref ReportingPlatformBucket
          NODE_ENV: production